
export const   resList = [
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "738246",
          name: "Biryani & Curries",
          uuid: "707e7ccf-adf6-43c8-9924-eb9655bd7a0c",
          city: "79",
          area: "Kankarbagh",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "18a70b64b4c006a5fd772669284cab17",
          cuisines: ["Biryani"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          slaString: "27 MINS",
          lastMileTravel: 2.5,
          slugs: {
            restaurant: "biryani-&-curries-kankarbagh-kankarbagh",
            city: "patna",
          },
          cityState: "79",
          address:
            "Lochan Enclave, Housing Board Colony, Kankarbagh, Patrakar Nagar, Patna, Bihar 800020, India",
          locality: "Housing Board Colony",
          parentId: 438391,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 2100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 2100,
            message: "",
            title: "Delivery Charge",
            amount: "2100",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "738246",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            lastMileTravel: 2.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: true,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "667349",
          name: "Magic Flames",
          uuid: "d3d2003f-ae77-45a8-a4be-bbed81823627",
          city: "79",
          area: "Patliputra Colony",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "cf0ef6cff803db3b621931fc867ebd9d",
          cuisines: ["Indian", "Chinese", "Biryani"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          slaString: "42 MINS",
          lastMileTravel: 6.699999809265137,
          slugs: {
            restaurant: "magic-flames-srikrishnapuri-srikrishnapuri",
            city: "patna",
          },
          cityState: "79",
          address:
            "27, opposite Laddo Gopal, Patliputra Colony, Patna, Bihar 800013, India",
          locality: "Patliputra guest house",
          parentId: 400252,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4400,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 5200,
            message: "",
            title: "Delivery Charge",
            amount: "5200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.6 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "₹100 OFF",
            subHeader: "ABOVE ₹199",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "667349",
            deliveryTime: 42,
            minDeliveryTime: 42,
            maxDeliveryTime: 42,
            lastMileTravel: 6.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "722559",
          name: "Wrapchick Crispy Fried Chicken",
          uuid: "c80a5629-f39e-4fc4-9a1d-b4b897bd5390",
          city: "79",
          area: "Srikrishnapuri",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "592d4782d10605236e6e22437cffc964",
          cuisines: ["Snacks", "Burgers"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          slaString: "45 MINS",
          lastMileTravel: 5,
          slugs: {
            restaurant:
              "wrapchick-crispy-fried-chicken-srikrishnapuri-srikrishnapuri",
            city: "patna",
          },
          cityState: "79",
          address: "1366, 2, Anandpuri, Patna, Bihar 800001, India",
          locality: "Anandpuri",
          parentId: 430214,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 3900,
            message: "",
            title: "Delivery Charge",
            amount: "3900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "722559",
            deliveryTime: 45,
            minDeliveryTime: 45,
            maxDeliveryTime: 45,
            lastMileTravel: 5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: true,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "455377",
          name: " 87 Cafe & Resto",
          uuid: "55db1931-d78b-4dba-b9e5-ae41e763305a",
          city: "79",
          area: "Rajeev Nagar",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "hzpabwagjx3uodmlgvnu",
          cuisines: ["Chinese", "Indian", "South Indian"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 52,
          minDeliveryTime: 52,
          maxDeliveryTime: 52,
          slaString: "52 MINS",
          lastMileTravel: 7.800000190734863,
          slugs: {
            restaurant: "a-tea-7-cafe-patliputra-colony-patliputra-colony",
            city: "patna",
          },
          cityState: "79",
          address:
            "Rajiv nagar main road Between 22 & 23 no., Infront of BOI ATM.",
          locality: "Rajeev Nagar",
          parentId: 329347,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4400,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 5200,
            message: "",
            title: "Delivery Charge",
            amount: "5200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "455377",
            deliveryTime: 52,
            minDeliveryTime: 52,
            maxDeliveryTime: 52,
            lastMileTravel: 7.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "725139",
          name: "BIRYANI HOUSE",
          uuid: "35235b6d-230f-430a-bdf5-5f70844d78b7",
          city: "79",
          area: "Srikrishnapuri",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "f594f4f63d3e00e93203f02d40e38d24",
          cuisines: ["Biryani", "North Indian", "Snacks"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 41,
          minDeliveryTime: 41,
          maxDeliveryTime: 41,
          slaString: "41 MINS",
          lastMileTravel: 5.599999904632568,
          slugs: {
            restaurant: "biryani-house-srikrishnapuri-srikrishnapuri",
            city: "patna",
          },
          cityState: "79",
          address:
            "Mahesh nagar road no 0 near new food point , Patna Sadar, Patna Sadar, Patna, Bihar - 800024",
          locality: "Mahesh nagar",
          parentId: 134,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 3900,
            message: "",
            title: "Delivery Charge",
            amount: "3900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "UPTO ₹50",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "725139",
            deliveryTime: 41,
            minDeliveryTime: 41,
            maxDeliveryTime: 41,
            lastMileTravel: 5.599999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: true,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "473944",
          name: "Sattuz Cafe",
          uuid: "72fe40de-9443-48f7-84e5-fb2d02e69729",
          city: "79",
          area: "Patliputra Colony",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "co59c6tnuqgox28fgtuv",
          cuisines: ["Bihari", "Indian", "Snacks"],
          tags: [],
          costForTwo: 19900,
          costForTwoString: "₹199 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 6.099999904632568,
          slugs: {
            restaurant: "sattuz-cafe-patliputra-colony-patliputra-colony",
            city: "patna",
          },
          cityState: "79",
          address:
            "Flat -103, Basudha Apartment, Patliputra Colony, Patna, Bihar 800013, India",
          locality: "North Sri Krishna Puri ",
          parentId: 284565,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 4400,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 5200,
            message: "",
            title: "Delivery Charge",
            amount: "5200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6 kms",
          hasSurge: false,
          sla: {
            restaurantId: "473944",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 6.099999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "343468",
          name: "Cake 24x7",
          uuid: "db240f6c-44af-47a0-a7fe-78291f24f0af",
          city: "79",
          area: "Rajendra Nagar",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "yuai9tmymsdhq4az9os2",
          cuisines: ["Indian"],
          tags: [],
          costForTwo: 28000,
          costForTwoString: "₹280 FOR TWO",
          deliveryTime: 47,
          minDeliveryTime: 47,
          maxDeliveryTime: 47,
          slaString: "47 MINS",
          lastMileTravel: 4.800000190734863,
          slugs: {
            restaurant: "cake-24x7-kankarbagh-kankarbagh",
            city: "patna",
          },
          cityState: "79",
          address:
            "SISODIA SADAN, M-3/18, ROAD N-11, RAJENDRA NAGAR PATNA, Patna City, Patna City, Patna, Bihar, 800016",
          locality: "Road No 12",
          parentId: 54688,
          unserviceable: true,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 2600,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 2600,
            message: "",
            title: "Delivery Charge",
            amount: "2600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.8 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "₹125 OFF",
            subHeader: "ABOVE ₹199",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "343468",
            deliveryTime: 47,
            minDeliveryTime: 47,
            maxDeliveryTime: 47,
            lastMileTravel: 4.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "2.8",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "550051",
          name: "The Backstreet Kitchen",
          uuid: "218db4b2-9d88-4e37-b608-3e2d477b27f2",
          city: "79",
          area: "Muhammadpur",
          totalRatingsString: "20+ ratings",
          cloudinaryImageId: "q9z8g0yx74eukrrlvqrw",
          cuisines: ["Chinese", "North Indian"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          slaString: "40 MINS",
          lastMileTravel: 5.900000095367432,
          slugs: {
            restaurant: "the-backstreet-kitchen-kankarbagh-kankarbagh",
            city: "patna",
          },
          cityState: "79",
          address:
            "plot no-841, India Machinary campus, west of kumhrar park, kumhrar, Patna- 800026, Patna Sadar, Patna, , Bihar, 800026",
          locality: "kumhrar park",
          parentId: 330666,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3100,
            message: "",
            title: "Delivery Charge",
            amount: "3100",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.9 kms",
          hasSurge: false,
          sla: {
            restaurantId: "550051",
            deliveryTime: 40,
            minDeliveryTime: 40,
            maxDeliveryTime: 40,
            lastMileTravel: 5.900000095367432,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.4",
          totalRatings: 20,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "503648",
          name: "Wat-a-Burger! - India ka Burger",
          uuid: "d3c4fdfc-b93c-4cdd-b95b-01ce756038c9",
          city: "79",
          area: "Kankarbagh",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "iryuriu78bi0mbyizjhu",
          cuisines: [
            "Burgers",
            "Fast Food",
            "Continental",
            "American",
            "Beverages",
            "Desserts",
          ],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          slaString: "33 MINS",
          lastMileTravel: 2.299999952316284,
          slugs: {
            restaurant: "wat-a-burger!-india-ka-burger-fraser-road-fraser-road",
            city: "patna",
          },
          cityState: "79",
          address:
            "S K 6, Sector-K, MalahiPakadiChowk,Kankarbagh, Patna Sadar, Patna, Bihar-800020",
          locality: "Malahi Pakadi Chowk",
          parentId: 384458,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 2100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 2100,
            message: "",
            title: "Delivery Charge",
            amount: "2100",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2.2 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "₹100 OFF",
            subHeader: "ABOVE ₹199",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "503648",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            lastMileTravel: 2.299999952316284,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "712257",
          name: "Fresh Fruit and Juice Collection",
          uuid: "4f76fb4c-bb79-4e33-af9c-703cf3833795",
          city: "79",
          area: "Srikrishnapuri",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "74f264c68e8c9b9c5f4c270cf996c882",
          cuisines: ["Beverages"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          slaString: "38 MINS",
          lastMileTravel: 5.599999904632568,
          slugs: {
            restaurant:
              "fresh-fruit-and-juice-collection-srikrishnapuri-srikrishnapuri",
            city: "patna",
          },
          cityState: "79",
          address: "Mahesh Nagar, Road No. 0, Near New Food Point, Patna-800024",
          locality: "Mahesh Nagar",
          parentId: 425425,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 3900,
            message: "",
            title: "Delivery Charge",
            amount: "3900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "UPTO ₹50",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "712257",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            lastMileTravel: 5.599999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: false,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "703874",
          name: "Rang De Basanti Cafe & Restraunt",
          uuid: "a5b418ab-1b7f-4cc8-8ea1-5dccb4039856",
          city: "79",
          area: "Kankarbagh",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "5b17fc2fe703cfaa5478f2994fdf2e1d",
          cuisines: [
            "Beverages",
            "Indian",
            "Chinese",
            "Tandoor",
            "Fast Food",
            "Biryani",
          ],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 5,
          slugs: {
            restaurant: "rang-de-basanti-cafe-&-restraunt-kankarbagh-kankarbagh",
            city: "patna",
          },
          cityState: "79",
          address:
            "RS PALACE WARD NO 45 MAHATAMA GANDHI NAGAR KANTI FACTORY ROAD ,Patna Sadar,Patna,Bihar-800020",
          locality: "Mahatama Gandhi Nagar",
          parentId: 421080,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3100,
            message: "",
            title: "Delivery Charge",
            amount: "3100",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "40% OFF",
            subHeader: "UPTO ₹80",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "703874",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "655421",
          name: "Singh Biryani",
          uuid: "747b8cc6-6f15-4b90-bd03-ee163e9c01de",
          city: "79",
          area: "Rajeev Nagar",
          totalRatingsString: "50+ ratings",
          cloudinaryImageId: "c49f74c4c8c4098a384c511817d7ebdf",
          cuisines: ["Indian", "Salads", "Snacks", "Chinese"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 44,
          minDeliveryTime: 44,
          maxDeliveryTime: 44,
          slaString: "44 MINS",
          lastMileTravel: 7.800000190734863,
          slugs: {
            restaurant: "singh-biryani-patliputra-colony-patliputra-colony",
            city: "patna",
          },
          cityState: "79",
          address:
            "Rajeev Nagar, Between Road No- 22 or 23, Patna Sadar, Patna, Bihar-800024",
          locality: "",
          parentId: 188385,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4400,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 5200,
            message: "",
            title: "Delivery Charge",
            amount: "5200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "655421",
            deliveryTime: 44,
            minDeliveryTime: 44,
            maxDeliveryTime: 44,
            lastMileTravel: 7.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.5",
          totalRatings: 50,
          new: false,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "343942",
          name: "BAKERY 24x7",
          uuid: "3ca4981c-9cdc-459b-9ac4-0527bedff38a",
          city: "79",
          area: "Kankarbagh",
          totalRatingsString: "20+ ratings",
          cloudinaryImageId: "fvjrccmv6j4lr2ldd6hd",
          cuisines: ["Bakery"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 46,
          minDeliveryTime: 46,
          maxDeliveryTime: 46,
          slaString: "46 MINS",
          lastMileTravel: 5,
          slugs: {
            restaurant: "bakery-24x7-kankarbagh-kankarbagh",
            city: "patna",
          },
          cityState: "79",
          address:
            "SISODIA SADAN, M-3/18, ROAD N-11, RAJENDRA NAGAR PATNA, Patna City, Patna City, Patna, Bihar, 800016",
          locality: "Kumharar",
          parentId: 3817,
          unserviceable: true,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3100,
            message: "",
            title: "Delivery Charge",
            amount: "3100",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "₹125 OFF",
            subHeader: "ABOVE ₹199",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "343942",
            deliveryTime: 46,
            minDeliveryTime: 46,
            maxDeliveryTime: 46,
            lastMileTravel: 5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "2.9",
          totalRatings: 20,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "599806",
          name: "Hasty Tasty",
          uuid: "e9d7509a-1c35-4f6e-ae6e-00d113a6b39c",
          city: "79",
          area: "Rajeev Nagar",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "gpqiiq6amnyf5huth5yk",
          cuisines: ["Indian", "Chinese", "Snacks", "South Indian"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 48,
          minDeliveryTime: 48,
          maxDeliveryTime: 48,
          slaString: "48 MINS",
          lastMileTravel: 7.800000190734863,
          slugs: {
            restaurant: "87's-spicy-bite-srikrishnapuri-srikrishnapuri",
            city: "patna",
          },
          cityState: "79",
          address:
            "RAJEEV NAGAR BETWEEN ROAD NO:- 22 OR 23, Patna Sadar, Patna, Bihar, 800024",
          locality: "Rajeev Nagar",
          parentId: 358143,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 4400,
                message: "",
              },
              {
                name: "special",
                fee: 800,
                message: "",
              },
            ],
            totalFees: 5200,
            message: "",
            title: "Delivery Charge",
            amount: "5200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "599806",
            deliveryTime: 48,
            minDeliveryTime: 48,
            maxDeliveryTime: 48,
            lastMileTravel: 7.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
        crouton: {
          type: "SPECIAL",
          metaInfo: {
            bgColor: "#282C3F",
            icon: "surge_listing_piuzrv",
            textColor: "#ffffff",
            title: "High Demand",
            message: "Surge fee of Rs ₹8 may be applicable",
          },
        },
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "604935",
          name: "Paris Cafe",
          uuid: "1cc2fcb9-729a-4164-958b-883b7431c415",
          city: "79",
          area: "Kankarbagh",
          totalRatingsString: "20+ ratings",
          cloudinaryImageId: "voudv4lpejihnxkft2bh",
          cuisines: ["Beverages", "Chinese", "Italian-American", "Fast Food"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 2.299999952316284,
          slugs: {
            restaurant: "paris-cafe-kankarbagh-kankarbagh",
            city: "patna",
          },
          cityState: "79",
          address:
            "K-Sector-1, P.C Colony, Hanuman Nagar, Lohiya Nagar, Patrakar Nagar, Patna Sadar, Patna, Bihar_ 800020",
          locality: "Hanuman Nagar",
          parentId: 155646,
          unserviceable: true,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 2100,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 2100,
            message: "",
            title: "Delivery Charge",
            amount: "2100",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "Closes soon",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2.2 kms",
          hasSurge: false,
          sla: {
            restaurantId: "604935",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 2.299999952316284,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE_WITH_BANNER",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 20,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "messageCard",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "messageCard",
        data: {
          message: "Opens next at 7 am, today",
        },
        subtype: "info",
        sticky: 1,
      },
      parentWidget: false,
    },
  ];
  
  const CDN_LINK="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"
  export default CDN_LINK;